title: PROSTUDIO
email: info@prosutiomoz.com
description: >- # this means to ignore newlines until "baseurl:"
  Videos & Fotografias
url: "https://prostudiomoz.com" # the base hostname & protocol for your site, e.g. http://example.com
image: /assets/img/prostudio.svg
logo: /assets/img/blacklogo.svg

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: assets/_sass

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2

permalink: pretty

collections_dir: collections
collections:
  covers:
  sobre:
  servicos:
    output: true
  galeria:

# Pagination Settings
pagination:
  enabled: false
  per_page: 20
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
